# app.py – Streamlit web application for AdoptFast
# Predict adoption speed and provide optimization suggestions.
# Requires the trained model and feature map files (generated by the notebook).

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# -------------------- Configuration --------------------
MODEL_PATH = 'models/random_forest_structured.pkl'
FEAT_IMP_PATH = 'outputs/feature_importance_structured.csv'
BREED_SPEED_PATH = 'outputs/breed_speed_map.csv'
FREQ_COLORS_PATH = 'outputs/freq_colors.csv'

# -------------------- Load assets --------------------
@st.cache_resource
def load_assets():
    model = joblib.load(MODEL_PATH)
    feat_imp = pd.read_csv(FEAT_IMP_PATH, index_col=0).squeeze("columns")
    # Load breed speed map (CSV with breeds as index and a single column)
    breed_speed = pd.read_csv(BREED_SPEED_PATH, index_col=0).squeeze("columns").to_dict()
    # Load list of frequent colors
    freq_colors = pd.read_csv(FREQ_COLORS_PATH, header=None).squeeze("columns").tolist()
    return model, feat_imp, breed_speed, freq_colors

model, feature_importance, breed_speed_map, freq_colors = load_assets()

# -------------------- Streamlit UI --------------------
st.set_page_config(page_title='AdoptFast', page_icon='🐾')
st.title('🐾 AdoptFast – Adoption Speed Predictor')
st.markdown('Enter a pet’s profile to predict how long it will wait for adoption.')

with st.form('pet_form'):
    col1, col2 = st.columns(2)
    with col1:
        animal_type = st.selectbox('Animal Type', ['Dog', 'Cat'])
        age_months = st.number_input('Age (months)', min_value=0, max_value=300, value=12, step=1)
        is_fixed = st.radio('Sterilized?', ['Yes', 'No'], horizontal=True)
        name = st.text_input('Name', value='Buddy')
        breed_name = st.selectbox('Breed', sorted(breed_speed_map.keys()))
    with col2:
        # Multi‑hot color input: user types colors separated by commas
        color_input = st.text_input('Color(s) (comma separated, e.g. Black,White)', value='Black')
        photo_count = st.slider('Number of Photos', 0, 20, 3)
        fee = st.number_input('Adoption Fee (RM)', min_value=0, value=0, step=10)
    submitted = st.form_submit_button('Predict Adoption Speed')

# -------------------- Prediction --------------------
if submitted:
    # Convert inputs to features
    age_days = age_months * 30
    is_fixed_int = 1 if is_fixed == 'Yes' else 0
    has_name = int(bool(name and name != 'No Name'))
    is_cat = 1 if animal_type == 'Cat' else 0
    breed_speed_mean = breed_speed_map.get(breed_name, 2.5)

    # Multi‑hot color encoding
    input_colors = [c.strip() for c in color_input.split(',') if c.strip()]
    color_features = {f'color_{c}': 1 if c in input_colors else 0 for c in freq_colors}

    # Build feature vector in the exact order used during training
    struct_base = ['age_days', 'breed_speed_mean', 'PhotoAmt', 'Fee', 'is_fixed', 'is_cat', 'has_name']
    color_cols = [f'color_{c}' for c in freq_colors]
    feature_order = struct_base + color_cols

    X = pd.DataFrame([{
        'age_days': age_days,
        'breed_speed_mean': breed_speed_mean,
        'PhotoAmt': photo_count,
        'Fee': fee,
        'is_fixed': is_fixed_int,
        'is_cat': is_cat,
        'has_name': has_name,
        **color_features
    }])[feature_order]

    # Predict probabilities
    proba = model.predict_proba(X)[0]
    pred_class = np.argmax(proba)
    speed_labels = ['Same Day', '1-7 Days', '8-30 Days', '31-90 Days', '90+ Days']

    st.success(f'Most Likely Adoption Time: **{speed_labels[pred_class]}** (confidence {proba[pred_class]:.1%})')

    # Probability bar chart
    st.subheader('📈 Probability Distribution')
    st.bar_chart(pd.DataFrame({'Probability': proba}, index=speed_labels))

    # Optimization suggestions
    st.subheader('💡 Optimization Suggestions')
    suggestions = []
    if photo_count < 3:
        suggestions.append('📸 Increase photos to 3–4 (optimal range).')
    elif photo_count > 5:
        suggestions.append('📸 Too many photos may reduce interest; consider using the 3–4 best ones.')
    if fee == 0:
        suggestions.append('💰 A modest adoption fee (e.g., RM 50‑200) can filter serious adopters and may increase perceived value.')
    if not has_name:
        suggestions.append('🏷️ Give the pet a warm, memorable name – it significantly helps adoption (especially for cats).')
    if not is_fixed_int:
        suggestions.append('⚕️ Sterilization greatly improves adoption speed, especially for cats.')
    if color_input and 'Black' in color_input:
        suggestions.append('🎨 Use bright, well‑lit photos to show the details of dark‑colored pets.')
    if not suggestions:
        suggestions.append('✅ This profile looks great! The pet has a strong chance of quick adoption.')
    for s in suggestions:
        st.write(f'- {s}')